# Generated by Django 5.1.4 on 2025-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('office', models.CharField(blank=True, max_length=500, null=True)),
                ('speciality', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('IND', 'Individual'), ('BUS', 'Business')], default='IND', max_length=25)),
                ('query_type', models.CharField(choices=[('SRV', 'Service Enquiry'), ('Prop', 'Request for Proposal'), ('GEN', 'General Enquiry')], default='SRV', max_length=25)),
                ('client_first_name', models.CharField(max_length=500)),
                ('client_last_name', models.CharField(max_length=500)),
                ('client_email', models.EmailField(max_length=500)),
                ('client_phone', models.CharField(max_length=15)),
                ('client_state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory'), ('International', 'International')], max_length=50)),
                ('client_postcode', models.CharField(max_length=10)),
                ('client_message', models.TextField(null=True)),
                ('client_business_name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('advisor', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
